### ISSUE TITLE
Toolbar button and auto preview

### ISSUE THREAD

**Issue by aminya** [atom-community/markdown-preview-plus#498] opened 2020-08-02 04:11 UTC
It would be nice if there was a tool-bar button and also automatic preview on opening a file.

**Comment by lierdakil** [comment] 2020-08-02 09:36
Atom doesn't have a default tool-bar, so I don't know what you're referring to. Besides, hotkey is generally more convenient than a button taking up space in the UI.

As for automatic preview on open, it's less useful than annoying IMO. But for those who want it, there's https://atom.io/packages/markdown-preview-plus-opener.

For the purposes of book-keeping, the second part is a duplicate of https://github.com/atom-community/markdown-preview-plus/issues/127

**Comment by aminya** [comment] 2020-08-02 23:10
I added the button in #499. Tool-bar is one of the most used packages of the Atom ecosystem. This button is added only for those who have it. It does not affect others.

**Closed** 2020-09-26 10:48 UTC
