### ISSUE TITLE
Preview not available

### ISSUE THREAD

**Issue by tusharnandy** [atom-community/markdown-preview-plus#491] opened 2020-06-08 05:30 UTC
Something has happened to this package in my machine. Whenever I try and click Ctrl+Shift+M, I get a black screen in the preview and nothing is displayed on it.
Please help
Thank you in advance

**Comment by tusharnandy** [comment] 2020-06-08 05:32
I am using ubuntu by the way

**Comment by jodh-intel** [comment] 2020-06-08 13:29
Same problem on F32.

**Comment by jodh-intel** [comment] 2020-06-08 13:38
I'm using atom version atom-1.47.0-0.1.

Might be a core problem as I see the same problem with https://atom.io/packages/markdown-preview-enhanced.

**Comment by lierdakil** [comment] 2020-06-08 13:47
Duplicate of https://github.com/atom-community/markdown-preview-plus/issues/487
Upstream issue: https://github.com/atom/atom/issues/20604

TL;DR: downgrade to 1.46 and wait for the next release. If you want to complain, complain to upstream. Sorry.

**Closed by lierdakil** 2020-06-08 13:47 UTC
