### ISSUE TITLE
Freezes on running basic file

### ISSUE THREAD

**Issue by AddemF** [atom-community/markdown-preview-plus#176] opened 2016-01-28 19:17 UTC
I have used this package successfully in the past but I just ran it on a .md file for the first time in a few months and now it freezes.  I uninstalled and then installed it, tried again, it still does the same thing.  I then ran it on a very simple file:

> # Title
> 
> $e = mc^2$

and it still freezes.  

Not sure what other info I should include in the issue, but I'm running Atom version 1.4.1 (latest update) on Windows 10.

**Comment by Galadirith** [comment] 2016-03-26 22:29
@AddemF Thanks for opening the issue and I really apologise for taking so long to reply.

Unfortunately I am not able to reproduce this issue. Are you still having this issue? If you are then I would be happy to investigate this further with your help. Thanks again.

**Comment by lierdakil** [comment] 2018-01-31 12:43
ETIMEDOUT, closing

**Closed by lierdakil** 2018-01-31 12:43 UTC
