### ISSUE TITLE
Pandoc CSS affects Atom GUI

### ISSUE THREAD

**Issue by fiapps** [atom-community/markdown-preview-plus#207] opened 2016-04-17 09:51 UTC
I was experiencing some weird issues with the Atom GUI when I opened the Markdown preview. This turns out to be because the GUI is being styled by the custom CSS I'm using with pandoc (`--css=/home/me/custom.css` specified in Pandoc Options: Commandline Arguments). My CSS contained this:

``` css
body {
    font-family: Cardo, serif;
    font-size: 16px;
    line-height: 22px;
    color: #737373;
    background-color: white;
    margin: 10px 13px 10px 13px;
}
@media screen and (min-width: 914px) {
    body {
        width: 854px;
        margin:10px auto;
    }
}
```

Now, at least the second of these is useless when previewing in Atom, so I've commented them out for now, but until I did, they were doing strange things to the GUI: once the Atom window was 914px or wider, all of the tabs would be inside an 854px wide block surrounded by broad white margins. If I opened the Atom Settings, it would pick up the large font size that the CSS was trying to apply to the preview. Even now, headings in the Settings tab pick up the font I set in the CSS for `h1, h2, h3, h4, h5, h6`.

**Comment by chrahunt** [comment] 2016-05-01 15:23
Which version of Atom are you using? I can't reproduce this on `1.8.0-beta3`. Can you try the beta version and report back?

**Comment by fiapps** [comment] 2016-05-06 09:34
I was using 1.7.3. I have now downloaded 1.8.0-beta3 and reproduced the issue.
![screen shot 2016-05-06 at 11 18 34 am](https://cloud.githubusercontent.com/assets/1018959/15069282/e54a846a-137c-11e6-82df-1f94b4254131.jpg)

If the preview is closed, the GUI returns to normal (full screen width), and the titles of packages in settings return to a sans serif font (from Palatino italic, specified in the CSS here).

![screen shot 2016-05-06 at 11 31 57 am](https://cloud.githubusercontent.com/assets/1018959/15069509/5b076aaa-137e-11e6-9a07-a43e695e1e48.jpg)

Note that to get this effect, it is necessary to select Enable Pandoc Parser and set Pandoc Options: Commandline Arguments to `--css=--css=/Users/me/Desktop/sample.css`. If the pandoc parser is not enabled, the custom CSS will not be used, and the Atom GUI will not be affected.

In case it matters: OS X 10.11.4, Pandoc 1.17.0.2.

**Comment by kysko** [comment] 2016-05-31 03:40
In fact, nothing to do with _pandoc_.
Disable the _pandoc_ parser, and insert the following inline code anywhere in your markdown text:
`<style>body{width:500px;}</style>`
and then use the preview: the GUI is shrinked.

It's not even limited to _markdown-preview-plus_: disable _markdown-preview-plus_ and re-enable the original _**markdown-preview**_. The preview of the file with the above added inline code will shrink the GUI.

Seems the html previews aren't sufficiently "wrapped"/"sandboxed" (or not at all!) in the above packages to prevent them (or some of their styles) from affecting the "host" GUI.

Now if you used that css code in the header of an HTML file (not a markdown file), and previewed it with the package _atom-html-preview_ (prepacked with Atom), the GUI doesn't shrink. Maybe because it's using the `<webview>` tag, maybe because that "wraps" it up safely.

Don't know enough about Atom (or Chromium, _coffee_, etc whatever) to correct the behavior, but I hope the above sheds some light as to what's going on.

**Comment by lierdakil** [comment] 2018-04-19 21:52
Closing in favour of #241

**Closed by lierdakil** 2018-04-19 21:52 UTC
