### ISSUE TITLE
image size issue

### ISSUE THREAD

**Issue by centell** [atom-community/markdown-preview-plus#311] opened 2017-10-18 09:58 UTC
I using [markdown-pdf](https://atom.io/packages/markdown-pdf) and it supply image sizing (`=[width]x[height]` )
but `![AWS](./img/image.png =200x110)` doesn't work in preview, so i report it.

**Comment by lierdakil** [comment] 2017-10-20 09:33
Hello. I'm sorry, but I'm pretty sure setting image size this way isn't standard Markdown by any stretch of the imagination. This looks more like image `alt` attribute is repurposed for image size (which is a dirty hack). Looking over CommonMark spec, there aren't any general-purpose ways to specify image size, so there won't likely be a universal solution. FWIW, Pandoc has its own syntax for specifying image attributes, including size -- don't know if it's any help in your particular use-case (probably not).

There's a non-generic solution, however: https://www.npmjs.com/package/markdown-it-imsize -- this should work with our default parser (markdown-it). I might find some time to try it out later this month, but in the meantime PRs are welcome.

**Comment by kiwi0fruit** [comment] 2017-12-12 05:34
Speaking about image size issues:
There is one on Windows when screen scale is set to more than 96 px per inch (for example to 120). May be it's also on Linux - who knows. It's actually a webkit/electron (and other browsers as well) bug.

It happen on images of low resolution. In order to look good their size should not exceed the real size in pixels. Browser keeps their size below the real size... in px. The problem is that the browser's px is larger when scale is larger. So the image is displayed stretched and a bit blurry. I doubt that this would be fixed on browser side (or we can help bring the onset of this event).

For now this can be fixed via setting image size: `![Pic caption](pic/img.png){#fig:1 style="max-height: 400px;"}` where `400px = real_size/1.25` for 1.25 scaled display. I guess this can be automated via js, I even tested [script](https://stackoverflow.com/questions/279749/detecting-the-system-dpi-ppi-from-js-css/35941703#35941703) (and it worked):

```js
function findFirstPositive(b, a, i, c) {
  c=(d,e)=>e>=d?(a=d+(e-d)/2,0<b(a)&&(a==d||0>=b(a-1))?a:0>=b(a)?c(a+1,e):c(d,a-1)):-1
  for (i = 1; 0 >= b(i);) i *= 2
  return c(i / 2, i)|0
}

var dpi = findFirstPositive(x => matchMedia(`(max-resolution: ${x}dpi)`).matches)

console.log(dpi)
```

I plan to fix in future...

**Closed** 2018-06-06 21:36 UTC
Labels: enhancement, good first issue
