### ISSUE TITLE
Incompatibility with NVATOM Plugin

### ISSUE THREAD

**Issue by johjeff** [atom-community/markdown-preview-plus#280] opened 2017-03-21 07:50 UTC
Hello,

I recently installed the NVATOM plugin to get Notational Velocity-like features in Atom. Upon installation, Markdown Preview Plus doesn't work. I have verified that if I disable the NVATOM plugin, Preview works again. I tried the Preview shortcut, as well as selecting it through the Plugins menu.

This is also the case with the regular Markdown-Preview that came with Atom. Not sure why it doesn't work - the command keys associated with NVATOM are alt-ctrl-l and alt-ctrl-o, so they shouldn't interfere with the ctrl-shift-m for Preview.

Thank you.

Jeff

**Comment by lierdakil** [comment] 2017-03-22 10:39
Well, I can't reproduce.

- Try opening MPP from command palette (`ctrl`+`shift`+`P` or something).
![image](https://cloud.githubusercontent.com/assets/7275622/24193837/b34f4fe8-0f04-11e7-8c55-098a7e065fcb.png)
- Check if something else steals the binding with 'Key Binding Resolver' (core Atom package):
![image](https://cloud.githubusercontent.com/assets/7275622/24193907/f765f718-0f04-11e7-9be9-3e96a27ac47a.png)

**Comment by lierdakil** [comment] 2017-03-22 10:42
Also check developer console for errors. Maybe that will provide some insight.

**Comment by lierdakil** [comment] 2017-03-22 10:43
(View → Developer → Toggle Developer Tools → Console)

**Comment by lierdakil** [comment] 2018-01-12 00:44
ETIMEDOUT, closing.

**Closed by lierdakil** 2018-01-12 00:44 UTC
Labels: needs-reproduction
