### ISSUE TITLE
MPP only support singl-line latex?

### ISSUE THREAD

**Issue by Pekary** [atom-community/markdown-preview-plus#279] opened 2017-03-19 08:16 UTC
such as 
- this is a x square $x^2$
but the chrome shows:
![image](https://cloud.githubusercontent.com/assets/11911116/24079299/68f10f28-0cbf-11e7-806b-57047a1e593d.png)

**Comment by lierdakil** [comment] 2017-03-19 08:32
I'm sorry, but I don't understand what the problem is. If math isn't rendered, did you remember to disable built-in `makrdown-preview` package? If you didn't it's entirely possible that you're looking at it instead of MPP.

**Comment by CarlosEvo** [comment] 2017-04-12 05:20
Multiple Line LaTeX math works for me by using `\\`

`$\frac{2.5 \times 10^{22} \times 1}{6.022\times 10^{23}mol}\\ = 0.0415mol\\ = 0.0415 \times 10^{-3}kmol$`

<img width="225" alt="screen shot 2017-04-11 at 10 19 13 pm" src="https://cloud.githubusercontent.com/assets/11689106/24942318/03f7b880-1f05-11e7-97b0-eed5ca232ea7.png">

**Comment by CarlosEvo** [comment] 2017-04-12 05:32
It seems that chrome does not support MathJax rendering, but there are plugins that do that, i.e. [Math Anywhere](https://chrome.google.com/webstore/detail/math-anywhere/gebhifiddmaaeecbaiemfpejghjdjmhc?hl=en)

**Comment by lierdakil** [comment] 2018-01-12 00:43
ETIMEDOUT, closing

**Closed by lierdakil** 2018-01-12 00:43 UTC
Labels: reply-needed
