### ISSUE TITLE
Uncaught error InvalidCharacterError in markdown-preview-plus webview client

### ISSUE THREAD

**Issue by ylqi007** [atom-community/markdown-preview-plus#486] opened 2020-05-06 22:41 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 16.04.6
**Thrown From**: [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus) package 3.11.5

### Stack Trace

Uncaught error InvalidCharacterError in markdown-preview-plus webview client

```
At Failed to execute 'setAttribute' on 'Element': '<pre' is not a valid attribute name.

stack:
Error: Failed to execute 'setAttribute' on 'Element': '<pre' is not a valid attribute name.
    at morphAttrs (/home/yq0033/.atom/packages/markdown-preview-plus/node_modules/morphdom/dist/morphdom.js:39:26)
    at morphEl (/home/yq0033/.atom/packages/markdown-preview-plus/node_modules/morphdom/dist/morphdom.js:497:17)
    at morphChildren (/home/yq0033/.atom/packages/markdown-preview-plus/node_modules/morphdom/dist/morphdom.js:605:33)
    at morphEl (/home/yq0033/.atom/packages/markdown-preview-plus/node_modules/morphdom/dist/morphdom.js:507:15)
    at morphdom (/home/yq0033/.atom/packages/markdown-preview-plus/node_modules/morphdom/dist/morphdom.js:722:13)
    at r.<anonymous> (file:///home/yq0033/.atom/packages/markdown-preview-plus/client/main.c39d6dcf.js:2:2047)
    at file:///home/yq0033/.atom/packages/markdown-preview-plus/client/main.c39d6dcf.js:2:1301
    at Object.next (file:///home/yq0033/.atom/packages/markdown-preview-plus/client/main.c39d6dcf.js:2:1406)
    at file:///home/yq0033/.atom/packages/markdown-preview-plus/client/main.c39d6dcf.js:2:319
    at new Promise (<anonymous>)

Error
    at HTMLElement.WebviewHandler._element.addEventListener (/packages/markdown-preview-plus/lib/markdown-preview-view/webview-handler.js:36:36)
    at WebViewImpl.dispatchEvent (/usr/share/atom/resources/electron.asar/renderer/web-view/web-view.js:126:22)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/renderer/web-view/guest-view-internal.js:81:15)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -0:32.3.0 snippets:expand (input.hidden-input)
     -0:32.3.0 editor:indent (input.hidden-input)
     -0:30.1.0 core:move-left (input.hidden-input)
     -0:29.3.0 core:move-right (input.hidden-input)
     -0:28.8.0 core:move-left (input.hidden-input)
  2x -0:28.4.0 core:move-right (input.hidden-input)
  6x -0:27.9.0 core:backspace (input.hidden-input)
     -0:26.3.0 snippets:next-tab-stop (input.hidden-input)
     -0:26.3.0 snippets:expand (input.hidden-input)
     -0:26.3.0 editor:indent (input.hidden-input)
     -0:26 snippets:next-tab-stop (input.hidden-input)
     -0:26 snippets:expand (input.hidden-input)
     -0:26 editor:indent (input.hidden-input)
  2x -0:25.6.0 editor:newline (input.hidden-input)
     -0:16 core:delete (input.hidden-input)
  2x -0:11.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
markdown-image-paste 2.5.2 
markdown-preview-plus 3.11.5 
```

**Comment by lierdakil** [comment] 2020-05-07 00:14
Seems like a duplicate of #470?

I honestly have no idea how to reproduce this. If you could describe how you got this error, that would dramatically increase the chance of it being fixed.

**Closed** 2020-07-15 14:34 UTC
Labels: duplicate, more-information-needed, needs-reproduction
