### ISSUE TITLE
TypeError: Cannot read property 'className' of null

### ISSUE THREAD

**Issue by anthillsocial** [atom-community/markdown-preview-plus#371] opened 2018-04-17 10:19 UTC
[Enter steps to reproduce:]

1. Preview markdown text as in html pane.
2. Right-click copy as html.

**Atom**: 1.25.1 x64
**Electron**: 1.8.4
**OS**: "Arch Linux"
**Thrown From**: [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus) package 2.5.7

### Stack Trace

TypeError: Cannot read property 'className' of null

```
At Cannot read property 'className' of null

TypeError: Cannot read property 'className' of null
    at /packages/markdown-preview-plus/lib/renderer.js:190:36
    at NodeList.forEach (<anonymous>)
    at tokenizeCodeBlocks (/packages/markdown-preview-plus/lib/renderer.js:188:33)
    at /packages/markdown-preview-plus/lib/renderer.js:38:20
    at callbackFunction (/packages/markdown-preview-plus/lib/renderer.js:52:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### Commands

```
     -0:09.1.0 core:copy (p.)
```

### Non-Core Packages

```
atom-music 0.7.0 
audio 1.5.7 
autocomplete-bibtex 1.2.1 
busy-signal 1.4.3 
color-picker 2.3.0 
file-header 1.13.9 
git-time-machine 1.5.9 
graphviz-preview 1.7.0 
hidpi 0.14.0 
intentions 1.1.5 
language-dot 1.7.0 
language-dot-template 0.2.0 
language-javascript-jsx 0.3.7 
language-latex 1.1.1 
language-pfm 0.82.0 
language-vue 0.23.1 
language-vue-component 0.5.0 
linter 2.2.0 
linter-js-standard-jsx 4.1.2 
linter-spell 0.15.0 
linter-ui-default 1.7.1 
markdown-preview-plus 2.5.7 
markdown-writer 2.7.3 
pandoc-convert 1.1.1 
process-palette 0.16.1 
quick-vue 0.1.0 
wordcount 2.10.4 
```

**Comment by lierdakil** [comment] 2018-04-17 10:52
Can't reproduce with the instructions given, but I guess the fix should be rather straightforward regardless. Thanks for your report, should be fixed in v2.5.8.

**Closed by lierdakil** 2018-04-17 10:52 UTC
