### ISSUE TITLE
Uncaught Error: The WebView must be attached to the DOM and the dom-ready event emitted before th...

### ISSUE THREAD

**Issue by wzdlc1996** [atom-community/markdown-preview-plus#458] opened 2019-06-03 05:04 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 4.1.4
**OS**: "Manjaro Linux"
**Thrown From**: [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus) package 3.8.1

### Stack Trace

Uncaught Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.

```
At /usr/lib/electron/resources/electron.asar/renderer/web-view/web-view.js:241

Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at getGuestInstanceId (/usr/lib/electron/resources/electron.asar/renderer/web-view/web-view.js:241:13)
    at HTMLElement.send (/usr/lib/electron/resources/electron.asar/renderer/web-view/web-view.js:272:77)
    at WebviewHandler.scrollSync (/packages/markdown-preview-plus/lib/markdown-preview-view/webview-handler.js:135:23)
    at disposables.add.atom.views.getView.onDidChangeScrollTop (/packages/markdown-preview-plus/lib/markdown-preview-view/markdown-preview-view-editor.js:117:26)
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at TextEditorComponent.setScrollTop (/usr/lib/atom/src/text-editor-component.js:2808:28)
    at TextEditorComponent.setScrollTopRow (/usr/lib/atom/src/text-editor-component.js:2859:30)
    at TextEditorComponent.flushPendingLogicalScrollPosition (/usr/lib/atom/src/text-editor-component.js:2024:31)
    at TextEditorComponent.didShow (/usr/lib/atom/src/text-editor-component.js:1467:12)
    at TextEditorComponent.didAttach (/usr/lib/atom/src/text-editor-component.js:1433:14)
    at HTMLElement.attachedCallback (/usr/lib/atom/src/text-editor-element.js:41:25)
    at HTMLElement.activeItemChanged (/usr/lib/atom/src/pane-element.js:152:22)
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at Pane.setActiveItem (/usr/lib/atom/src/pane.js:439:20)
    at Pane.activateItemAtIndex (/usr/lib/atom/src/pane.js:562:17)
    at Pane.activatePreviousItem (/usr/lib/atom/src/pane.js:526:12)
    at Pane.removeItem (/usr/lib/atom/src/pane.js:698:14)
    at Pane.destroyItem (/usr/lib/atom/src/pane.js:779:10)
```

### Commands

```
  2x -1:43.3.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
advanced-open-file 0.16.8 
atom-beautify 0.33.4 
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
atom-miku 2.2.5 
atom-runner 2.7.1 
autocomplete-html-entities 0.2.0 
autocomplete-paths 2.12.2 
autocomplete-python 1.14.0 
busy-signal 2.0.1 
emmet 2.4.3 
git-plus 8.6.3 
ide-python 1.4.1 
intentions 1.1.5 
jumpy 5.0.2 
language-latex 1.2.0 
language-markdown 0.37.0 
latex 0.50.2 
latexer 0.3.0 
linter 2.3.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
linter-write-good 0.9.2 
markdown-preview-enhanced 0.16.0 
markdown-preview-plus 3.8.1 
markdown-table-editor 1.1.2 
node_modules undefined 
open-in-browsers 0.0.30 
pigments 0.40.2 
platformio-ide-terminal 2.9.1 
python-debugger 0.2.0 
python-tools 0.6.9 
script 3.18.1 
```

**Comment by lierdakil** [comment] 2019-08-07 13:21
Duplicate of #456. TL;DR we can't support Atom built against Electron 4.1.4, since it's apparently an unofficial hack. This does not, to my knowledge, reproduce on the official Atom release.

**Closed by lierdakil** 2019-08-07 13:21 UTC
