### ISSUE TITLE
Feature Request: snap to change

### ISSUE THREAD

**Issue by cbourke** [atom-community/markdown-preview-plus#366] opened 2018-04-06 15:25 UTC
Is it possible (already?) to have the preview pane "snap" to the last change in the document?  This feature is present in Marked 2 and it would be nice to have something similar in this plugin.

**Comment by lierdakil** [comment] 2018-04-09 00:43
Probably duplicate of #133, #152, #177, see also #198. This project is understaffed, and this is somewhat complicated, so this has been haunting the backlogs for a while with little apparent progress. Help is welcome.

**Closed** 2018-04-23 00:56 UTC
