### ISSUE TITLE
pandoc-eqnos filter breaks syncing

### ISSUE THREAD

**Issue by mrkwjc** [atom-community/markdown-preview-plus#446] opened 2018-12-17 13:44 UTC
Hi!

I'd like to report that the preview syncing is not working when using pandoc renderer with pandoc-eqnos filter and with math rendering activated. Turning off the math rendering restores syncing.

I tried switching some MPP options, i tried also --standalone pandoc option but nothing helped. Any ideas?

Example: [m.txt](https://github.com/atom-community/markdown-preview-plus/files/2686245/m.txt)

Regards,
Marek

**Comment by lierdakil** [comment] 2018-12-17 14:07
Hi. Syncing with pandoc is at best anemic currently, and at worst completely broken. The reason is straightforward, pandoc doesn't report any meaningful source location information, so we have to rely on brittle heuristics. So frankly the fact it's broken with third-party filters is no surprise at all.

There have been talk of adding something like source maps to pandoc, but nothing has been done yet. I might eventually try my hand at this myself, but, one, there's no guarantee my code will get into pandoc, and two, filters would still be a problem in any system I can think of at the moment.

So yeah... Not much can be done about this currently, at least not quickly.

For the purpose of bookkeeping, this is a duplicate of #106

**Comment by mrkwjc** [comment] 2018-12-18 09:23
Thank you for this comprehensive answer despite the lack of good news. I hope however the problem will be solved in the future. Working preview would be very nice because pandoc along with the numbering filters is a great tool for scientific writing...

**Closed** 2020-07-15 14:34 UTC
Labels: duplicate
