### ISSUE TITLE
Add Support For Checkbox Styling of Lists (i.e. "Task Lists") 

### ISSUE THREAD

**Issue by bsandrow** [atom-community/markdown-preview-plus#186] opened 2016-03-02 23:03 UTC
``` markdown
* [ ] One
* [x] Two
```

should render as:
- [ ] One
- [x] Two

But currently renders as:
- &lsqb;&rsqb; One
- &lsqb;&NoBreak;x&rsqb; Two

Note: Don't copy-paste the "currently rendered as", because I had to insert some unicode characters to get Github's rendering to stop rendering it as a task list.

**Comment by wedi** [comment] 2017-02-01 23:43
This is actually implemented but there is a bug in the preview that adds a bullet point that shouldn’t be there.

To reproduce use this text:
```
- [ ] A line that doesn't wrap. Everything is fine.
- [ ] A line that wraps once. You see the bullet in the seconds line? It shouldn't be there. 
- [ ] A line that is long enough to cause some more line breaks to make clear everything is fine on all lines exept the last one. See? There is no bullet on the middle lines but one on the last one. That bullet shouldn't be there.
- This is a standard bullet point created with "-". See, it's the same that gets shown on the last line of a bullet point with a checkbox. Here everything is fine.
```

It is rendered like this:
<img width="478" alt="bildschirmfoto 2017-02-02 um 00 39 36" src="https://cloud.githubusercontent.com/assets/1466269/22531271/38abbd52-e8e0-11e6-9a50-d68adbc5a8e0.png">

Atom 1.13.1
markdown-preview-plus 2.4.1

**Comment by brandoncurtis** [comment] 2017-02-06 02:51
@wedi, as #251 also mentions, it's not rendering like that for me:

![no-tasks](https://cloud.githubusercontent.com/assets/2591290/22632795/32fcf26a-ebd1-11e6-9f00-ae1a1789c6a3.png)

atom 1.13.0
markdown-preview-plus@2.4.1
(with markdown-preview disabled, in a fresh $ATOM_HOME)

```html
<span class="syntax--source syntax--gfm">
    <span class="syntax--variable syntax--unordered syntax--list syntax--gfm">
        -
        </span>
    [ ] A line that doesn't wrap. Everything is fine.
    </span>
```

Simultaneously enabling `markdown-preview` gives me what you see:

![task-both](https://cloud.githubusercontent.com/assets/2591290/22633001/b057f204-ebd2-11e6-912e-b9ffb778ea5f.png)

...but the install instructions say to disable `markdown-preview` when `markdown-preview-plus` is enabled.

No change in the css of the task list item:

```html
<span class="syntax--source syntax--gfm">
    <span class="syntax--variable syntax--unordered syntax--list syntax--gfm">
        -
        </span>
    [ ] A line that doesn't wrap. Everything is fine.
    </span>
```

Checking or unchecking 'Use GitHub Styles' doesn't help.

**Comment by wedi** [comment] 2017-02-07 11:55
True. I haven’t disabled `markdown-preview`!
With `markdown-preview` disabled the above bullet point problem is gone but the checkboxes aren’t rendered.

**Comment by lierdakil** [comment] 2017-02-17 00:21
It should be relatively easy to extend markdown-it parser to convert `[ ]` and `[x]` at the start of list items into checkboxes. Anyone willing to try their hand at this is more than welcome to.

**Comment by ondono** [comment] 2017-10-18 14:25
I've been trying to track this down (I have no idea of half of the programming languages involved, but anyway). I don't know how helpful this is, but this is what I've figured out so far:

- markdown-preview has issues with the checkbox too. They seem to have a fix for it that's yet to be merged.
- markdown-preview-plus does NOT render checkboxes at all. 

I think part of the confusion above is about one package "shadowing" the other (possibly because they we're triggered via shortcut?).

I'm trying to find out where and how the rendering from markdown to html is done, but so far I have no clue.

**Comment by ondono** [comment] 2017-10-19 09:19
I've been able to do it, but I don't feel confortable doing a pull request until someone who actually knows what they're doing gives it an ok. 

https://github.com/ondono/markdown-preview-plus

**Comment by lierdakil** [comment] 2017-10-20 12:47
@ondono 

First of all, thank you very much for taking time to investigate this issue and prototyping the solution!

I'm not sure why you feel reluctant in creating a pull request. The point of PRs is those can be discussed/reviewed/updated, so please don't feel shy creating those. I did look over the last commit in your fork, and it seems fine at first glance, but I do have a couple questions, which would be easier to ask if you created a PR, but I will ask them here anyway.

- Why pass `enabled`? It would make checkboxes toggle-able by clicking on them, but problem is, Markdown source won't change from toggling checkboxes in preview. So I don't see much point in enabling them.
- Is there a purpose in adding an empty line before `if lazyHeaders`, or is it just a typo? I suspect *something* on CI will complain about that.
- Speaking of CI, could you add some tests for the feature? I'll gladly merge regardless, but having tests is generally a good idea.

Please create a PR first so that we could continue the discussion there (if needed). Thank you.

**Comment by ondono** [comment] 2017-10-23 08:19
@lierdakil 
My main concern is that I have pretty much any idea of coffescript (my work is mostly on hardware), I figured it out by testing, so while it was straightforward I wasn't sure I wasn't doing anything that went against good practices. Since they're literally two lines of code, I thought it would be wise to wait for someone to look at it.

> Why pass enabled? It would make checkboxes toggle-able by clicking on them, but problem is, Markdown source won't change from toggling checkboxes in preview. So I don't see much point in enabling them.

I thought the same, but since this was more of a functional decision I left it tbd.

> Is there a purpose in adding an empty line before if lazyHeaders, or is it just a typo? I suspect something on CI will complain about that.

Probably I typo while I tested things around.

> Speaking of CI, could you add some tests for the feature? I'll gladly merge regardless, but having tests is generally a good idea.

Now that you've seen it and I've haven't messed up things big time, I'm going to look at adding some tests and trying to set up all properly for a PR.

**Closed** 2018-01-29 13:52 UTC
Labels: enhancement
