### ISSUE TITLE
Doesn't work with pandoc-crossref?

### ISSUE THREAD

**Issue by jharrison** [atom-community/markdown-preview-plus#203] opened 2016-04-07 19:06 UTC
If I insert an image and give it a crossref tag like so:

```
![Caption](chart.png){#fig:chart}
```

And then try to reference it like this:

```
Here's a reference to [@fig:chart].
```

I get this in my preview tab:

<h1>Pandoc Error:</h1><p><b>pandoc exited with code 1: pandoc: [object Object]: openFile: does not exist (No such file or directory)<br></b></p><hr>

I know I have pandoc-crossref installed properly because when I run pandoc from the command line (or from script) it works just fine and my figures are referenced and numbered correctly.

In case it's relevant, in my settings I have Pandoc options set to:

```
--smart, --filter pandoc-crossref, --filter pandoc-citeproc, --highlight-style haddock
```

**Comment by kcyarn** [comment] 2016-05-06 23:55
I'm running into a similar issue with pandoc-include. After changing 

`--filter /home/user/pandoc-include/IncludeFilter.hs `

to

` --filter=/home/user/pandoc-include/IncludeFilter.hs`

I no longer see the code 1 error. However, the output acts as if the filter is never called. Only the markdown within the file itself is viewable.

Pandoc compiles documents perfectly with the filter enabled via commandline.

Markdown Preview Plus 2.4.0, Atom 1.5.3, Kubuntu 16.04

**Comment by jharrison** [comment] 2016-05-09 15:16
Thanks for the suggestion, but this didn't have any effect in my case.

Markdown Preview Plus 2.4.0, Atom 1.7.3, OSX 10.10.5

**Comment by seanpue** [comment] 2016-07-26 17:05
@jharrison Do you have Pandoc: Citations enabled? If so, the problem may be that  pandoc-citeproc is loaded before the Command Line Arguments. I have had the same error message with pandoc-figs because of that. Changing the line :
`args = _.union args, atom.config.get('markdown-preview-plus.pandocArguments')`
to 
`args = _.union atom.config.get('markdown-preview-plus.pandocArguments'), args`
in lib/pandoc-helper.coffee
fixed it for me. 
That will be in .atom/packages/markdown-preview-plus/lib/pandoc-helper.coffee on OS X. I will submit a pull request.

**Comment by fungs** [comment] 2016-09-30 10:32
I can confirm that this fixes the issue. The pandoc-crossref documentation also explicitly mentions that the filter must be applied before the pandoc-citeproc filter. Maybe, this can be resolved more generally in future but this fix works for me now. Thanks @jharrison!

Any chance to get this little change into the official release?

**Comment by carsonfarmer** [comment] 2016-10-18 04:04
👍 I can also confirm this fixes the issue. Hopefully this gets integrated into the next release?

**Comment by lierdakil** [comment] 2018-01-31 13:02
Fixed a while back, open new issues if still experiencing problems post v2.5.1.

**Closed by lierdakil** 2018-01-31 13:02 UTC
Labels: bug

**Comment by YuHuang3019** [comment] 2018-09-17 21:17
@seanpue Hi can you tell me how to find the lib/pandoc-helper.coffee file on mac? I am really new to atom and macbook... I would appreciate it if you could help!
